name = "WhereTheWaterFlows"
uuid = "ea906314-1493-4d22-a0af-f886a20c9fba"
authors = ["Mauro Werder <mauro3@runbox.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
